// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProPhoneService.Infrastructure.EfCore.Migrations
{
    /// <inheritdoc />
    public partial class AddPreferredVisitAt : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTime>(
                name: "preferred_visit_at",
                table: "repair_order",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.CreateIndex(
                name: "IX_repair_order_preferred_visit_at",
                table: "repair_order",
                column: "preferred_visit_at");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_repair_order_preferred_visit_at",
                table: "repair_order");

            migrationBuilder.DropColumn(
                name: "preferred_visit_at",
                table: "repair_order");
        }
    }
}
