// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace ProPhoneService.Infrastructure.EfCore.Migrations
{
    /// <inheritdoc />
    public partial class SeedPriceList : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "service",
                columns: new[] { "id", "description", "is_active", "name", "price" },
                values: new object[,]
                {
                    { new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e01"), null, true, "Диагностика (выявление неисправности)", 0m },
                    { new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e02"), null, true, "Замена дисплейного модуля", 1500m },
                    { new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e03"), null, true, "Замена разъема зарядки", 1200m },
                    { new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e04"), null, true, "Замена аккумулятора", 1500m },
                    { new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e05"), null, true, "Замена микрофона", 1500m },
                    { new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e06"), null, true, "Замена динамика", 1100m },
                    { new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e07"), null, true, "Замена кнопки", 1200m },
                    { new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e08"), null, true, "Замена камеры", 1500m },
                    { new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e09"), null, true, "Профилактика", 1000m },
                    { new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e10"), null, true, "Чистка сеток и разъемов", 700m }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "service",
                keyColumn: "id",
                keyValue: new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e01"));

            migrationBuilder.DeleteData(
                table: "service",
                keyColumn: "id",
                keyValue: new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e02"));

            migrationBuilder.DeleteData(
                table: "service",
                keyColumn: "id",
                keyValue: new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e03"));

            migrationBuilder.DeleteData(
                table: "service",
                keyColumn: "id",
                keyValue: new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e04"));

            migrationBuilder.DeleteData(
                table: "service",
                keyColumn: "id",
                keyValue: new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e05"));

            migrationBuilder.DeleteData(
                table: "service",
                keyColumn: "id",
                keyValue: new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e06"));

            migrationBuilder.DeleteData(
                table: "service",
                keyColumn: "id",
                keyValue: new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e07"));

            migrationBuilder.DeleteData(
                table: "service",
                keyColumn: "id",
                keyValue: new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e08"));

            migrationBuilder.DeleteData(
                table: "service",
                keyColumn: "id",
                keyValue: new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e09"));

            migrationBuilder.DeleteData(
                table: "service",
                keyColumn: "id",
                keyValue: new Guid("6f0d2a71-3f2e-4b1e-9d1f-0a1b2c3d4e10"));
        }
    }
}
