// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProPhoneService.Infrastructure.EfCore.Migrations
{
    /// <inheritdoc />
    public partial class AddPreferredVisitAt : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_repair_order_service_service_service_id",
                table: "repair_order_service");

            migrationBuilder.AddColumn<DateTime>(
                name: "preferred_visit_at",
                table: "repair_order",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_repair_order_preferred_visit_at",
                table: "repair_order",
                column: "preferred_visit_at");

            migrationBuilder.AddForeignKey(
                name: "FK_repair_order_service_service_service_id",
                table: "repair_order_service",
                column: "service_id",
                principalTable: "service",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_repair_order_service_service_service_id",
                table: "repair_order_service");

            migrationBuilder.DropIndex(
                name: "IX_repair_order_preferred_visit_at",
                table: "repair_order");

            migrationBuilder.DropColumn(
                name: "preferred_visit_at",
                table: "repair_order");

            migrationBuilder.AddForeignKey(
                name: "FK_repair_order_service_service_service_id",
                table: "repair_order_service",
                column: "service_id",
                principalTable: "service",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
