// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProPhoneService.Infrastructure.EfCore.Migrations
{
    /// <inheritdoc />
    public partial class AddCompositeIndexStatusCreatedAt : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_repair_order_status",
                table: "repair_order");

            migrationBuilder.CreateIndex(
                name: "IX_repair_order_status_created_at",
                table: "repair_order",
                columns: new[] { "status", "created_at" },
                descending: new[] { false, true });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_repair_order_status_created_at",
                table: "repair_order");

            migrationBuilder.CreateIndex(
                name: "IX_repair_order_status",
                table: "repair_order",
                column: "status");
        }
    }
}
